language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install -e .
  - pip install moto coverage nose

script:
  - nosetests --with-coverage --cover-package=storagelayer --cover-erase

after_success:
  # push tag as well
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      python setup.py sdist bdist_wheel ;
      twine upload dist/* ;
    fi
