language: python
python:
  - "3.6"

env:
  global:
    - BOTO_CONFIG=/dev/null

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libicu-dev
  - sudo rm -f /etc/boto.cfg

install:
  - pip install -e .
  - pip install boto==1.9.71 botocore==1.12.71 moto==1.3.7 coverage nose twine pyicu

script:
  - nosetests --with-coverage --cover-package=storagelayer --cover-erase

after_success:
  # push tag as well
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      python setup.py sdist bdist_wheel ;
      twine upload dist/* ;
    fi
